sonar.projectKey=ESP32-C6-Zigbee-Plant-Monitor
sonar.projectName=ESP32-C6-Zigbee-Plant-Monitor
sonar.projectVersion=1.0

sonar.scm.exclusions.disabled=true

# On force le scanner à regarder PARTOUT à partir de sa position
sonar.sourceEncoding=UTF-8

sonar.sources=main
sonar.exclusions=**/build/**,**/managed_components/**,**/.git/**,.DS_Store
sonar.cxx.file.suffixes=.c,.h

# C/C++ analysis using compilation database
#sonar.cfamily.compile-commands=build/compile_commands.json
sonar.cxx.compile_commands.path=build/compile_commands.json

# Server + auth (mieux via variables d'env dans CI)
sonar.host.url=http://localhost:9000
sonar.token=sqp_6943d6351f3378919231683780211ca3237746d5
